### ISSUE TITLE
Replace `hardinfo` with `hardinfo2`

### ISSUE THREAD

**Issue by arnulfj** [RebornOS-Team/calamares-configuration#27]
more information about the hardware

**Comment by pvshvp-oss** [comment]
I see that the `hardinfo` project is already decomissioned. We should replace it with `hardinfo2`.

This can happen after `hardinfo2` is added to our repositories. I have already notified @SoulHarsh007 on Discord, but tagging here for tracking purposes.

**Comment by SoulHarsh007** [comment]
@pvshvp-oss `hardinfo2` is now in RebornOS repositories.

**Comment by pvshvp-oss** [comment]
The welcome app has it and it is in the repositories too. Closing this issue as done.
